### ISSUE TITLE
Can you explain boot-args?

### ISSUE THREAD

**Issue by asle** [zanderzhng/EFI_Asrock_Z390_Phantom_ITX_OC#1]
Thanks for great setup. My i7-8700k on Asrock z390 Phantom ITX works great. But can you explain the boot-args section? It is for 3d party broadcom wifi/bt. https://github.com/acidanthera/BrcmPatchRAM - I have had a lot of sleep problems. Should this maybe fix that?

**bpr_probedelay=100 bpr_initialdelay=300 bpr_postresetdelay=300 brcmfx-country=#a**

With your boot-args my wifi/bt works but I have a Lenovo 4352. 
I also have a Radeon RX580 8GB. I had this below before and thought I needed it for full acceleration for the RX580? Also do I not need **keepsyms=1** ?

**-v keepsyms=1 agdpmod=pikera**

I always get to the boot window like holding down ALT on a real mac. But I always have to click on "Macintosh HD" to start. How to get automatic boot from main HD? Also is it possible to show Recovery HD? What about Windows since I have a Windows10 drive also?

**Comment by zanderzhng** [comment]
Hi Asle,

Thank you for looking into my configs.

#### bpr_blah boot argts
These boot-args were supposed to fix my DW1820A.
My DW1820A bluetooth used to fail like once a month, and I learnt from [daliansky](https://blog.daliansky.net/DW1820A_BCM94350ZAE-driver-inserts-the-correct-posture.html) that these boot-args could fix the failure after waking from sleep.
I can't say for sure if these boot-args fixed my problem yet.
I'm planning to switch back to BCM94360CS2 later to compare their performance.

#### -v keepsyms=1 agdpmod=pikera
**-v** means verbose boot log.
**keepsyms=1** something related to debug, use with debug=**0x100**.
**agdpmode=pikera** For people with NAVI GPUs (RX5xxx).
You may find more detailed explains in this [OpenCore Desktop Guide](https://dortania.github.io/OpenCore-Desktop-Guide/config.plist/coffee-lake.html)

#### Boot Selection
This is a known bug in OpenCore, if you enable customized GUI.
Future version might fix it.
Currently you have to hit enter manually.

#### Recovery HD
There are several configs regarding showing/hiding a partition in boot selection. You should look into **ScanPolicy** and **HideAuxiliary** in OpenCore's configuration pdf.

**Comment by asle** [comment]
Thanks for your kind reply. Do you have any sleep problems? I see my PCI address for WiFi is different from yours (I have lenovo card). The hackintosh behaves nice for a couple of days, then will not wake so I have to restart. The log says "sleep from wake failure" but can not see enough details pointing to what fails. i have a correct USB.kext (should be) but can not find the problem. So I should replace the PCI address to my card? I also would like to try a better ngff WiFi card but they are expensive and there is not enough height to use original Apple WiFi with adapter.

Read your links. Thanks!

~asle

**Comment by zanderzhng** [comment]
Hi Asle,

Address shouldn't change since we're using same motherboard. I assume you're talking about the vendor and device. (pci14e4,43a3).
I don't recognize the card **Lenovo 4352**, but you may look into [this thread](https://osxlatitude.com/forums/topic/11322-broadcom-bcm4350-cards-under-high-sierramojavecatalina/)

My sleep and wake works pretty well now, I sleep my computer several times per day without any issue. It used to wake up itself immediately after sleeping, or in the midnight, or refuse to sleep(stop all the fans), but all these problem had gone since some configs update.

**Comment by asle** [comment]
Thanks,
My wifi/bt card has a different device than your 1802A
 pci14e4,43b1
Could that make a difference? I Read the thread at osxlatitude.com and he enters
Key = compatible | Value = pci14e4,4353 | Type = STRING
You have entered pci14e4,43a0

My problem now is bluetooth does not see any devices. I suspect it has not loaded firmware, I read this thread (https://www.insanelymac.com/forum/topic/339175-brcmpatchram2-for-1015-catalina-broadcom-bluetooth-firmware-upload/) and this:

You will know the firmware is uploaded when its version in About This Mac->System Report...->Bluetooth shows something like: Firmware Version: v14 c5668. If it shows 4096 then the upload has failed.

My BT info shows: Firmware Version:  v14 c4096

I have tried with different Brcm kexts. It seems I need this to get wifi working
BrcmBluetoothInjector.kext
BrcmPatchRAM3.kext

There is no difference when I have these also included:
BrcmFirmwareData.kext
BrcmPatchRAM2.kext

But on https://github.com/RehabMan/OS-X-BrcmPatchRAM it says about BrcmBluetoothinjector.kext  to not mix with these last 2.
Do not use any of the other kexts (BrcmPatchRAM, BrcmPatchRAM2, BrcmFirmwareRepo, or BrcmFirmwareData) with this kext.

Before I upgraded to OpenCore I used Clover and wifi and BT worked great with these kexts
BrcmFirmwareData.kext
BrcmPatchRAM2.kext

Any ideas about this?


~asle

**Comment by asle** [comment]
Hi,
Just to say I am good to go now with my BCM20702A0 wifi/bt card.

I am not sure exactly why this is working great again but I can connect devices again. AirDrop works great also!
I also see now in System Report -> Bluetooth:
Firmware Version: v14 c5876 (was C4096)

Here is what I did:
-Upgraded to OC 0.5.8
-Upgraded all kexts, careful to get latest Brcm kexts
-Made sure the Brcm kexts were loaded in this order:

AirportBrcmFixup.kext
BrcmBluetoothInjector.kext
BrcmFirmwareData.kext
BrcmPatchRAM3.kext

I tried different mixes of Brcm kexts but it seems the BrcmPatchRAM3.kext is what I needed (nor RAM2) for my BCM20702A0.

The last thing I did was to upgrade OpenCanopy.efi for my boot menu. I also upgraded the Resources folder. When I restarted (for 100th time?) I got the nice icons and a "Reset NVRam" choice. I chose that and voila Bluetooth works! Lets hope it stays that way.

regards,

**Comment by zanderzhng** [comment]
@asle I'm glad you solved your BLE problem.

Regarding the question about kexts instructions, the information on Rehabman's BrcmPatchRam has been outdated for very long time.
You should refer to this link [Wireless Buyer Guide](https://dortania.github.io/Wireless-Buyers-Guide/types-of-wireless-card/m2.html)

I didn't find detailed information about BCM20702A0, it seems to be an USB BLE dongle.


Also, with recent updates, auto boot countdown has been fixed. Please refer to my recent builds.
